//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from oopLab1.g4 by ANTLR 4.13.1

#pragma warning disable 0162
#pragma warning disable 0219
#pragma warning disable 1591
#pragma warning disable 419

namespace oopLab1.Parser;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="oopLab1Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IoopLab1Visitor<Result> : IParseTreeVisitor<Result>
{
    /// <summary>
    /// Visit a parse tree produced by <see cref="oopLab1Parser.parse"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitParse([NotNull] oopLab1Parser.ParseContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>ComparisonExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitComparisonExpr([NotNull] oopLab1Parser.ComparisonExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>NotExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitNotExpr([NotNull] oopLab1Parser.NotExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>PowerExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitPowerExpr([NotNull] oopLab1Parser.PowerExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>MulDivExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitMulDivExpr([NotNull] oopLab1Parser.MulDivExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>AddSubExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitAddSubExpr([NotNull] oopLab1Parser.AddSubExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>FuncExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitFuncExpr([NotNull] oopLab1Parser.FuncExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>ParenExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitParenExpr([NotNull] oopLab1Parser.ParenExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>AtomExpr</c>
    /// labeled alternative in <see cref="oopLab1Parser.expr"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitAtomExpr([NotNull] oopLab1Parser.AtomExprContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>NumberAtom</c>
    /// labeled alternative in <see cref="oopLab1Parser.atom"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitNumberAtom([NotNull] oopLab1Parser.NumberAtomContext context);

    /// <summary>
    /// Visit a parse tree produced by the <c>CellAtom</c>
    /// labeled alternative in <see cref="oopLab1Parser.atom"/>.
    /// </summary>
    /// <param name="context">The parse tree.</param>
    /// <return>The visitor result.</return>
    Result VisitCellAtom([NotNull] oopLab1Parser.CellAtomContext context);
}